language: python
python:
  - "2.7"
install:
  - pip install -r test-requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
script:
  - python --version
  - python -m unittest discover -v
  - coverage run -m unittest discover
after_success:
  - coveralls
  - codeclimate-test-reporter
