language: python
python:
  - "2.7"
install:
  - pip install -r test-requirements.txt
  - pip install coveralls
script:
  - python --version
  - python -m unittest discover -v
  - coverage run sample.py
after_success:
  coveralls
